import StretchBackground from '@/components/StretchBackground';
import Header from '@/components/Header';
import '@/styles/globals.scss';
import './layout.scss';
import Footer from '@/components/Footer';
import ScrollUp from '@/components/ScrollUp';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="wrap">
          <StretchBackground imageWidth={1440} />
          <div className="background-lines">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>
          <ScrollUp />

          <Header />

          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
